language: generic
services:
  - docker

env:  
  matrix:
    - ROS_DISTRO="kinetic" _GUARD_INTERVAL=10 CATKIN_PARALLEL_JOBS='-p2' ROS_PARALLEL_JOBS='-j2' NOT_TEST_BUILD='true' NOT_TEST_INSTALL='true'
    - ROS_DISTRO="kinetic" _GUARD_INTERVAL=10 CATKIN_PARALLEL_JOBS='-p2' ROS_PARALLEL_JOBS='-j2' NOT_TEST_BUILD='true' NOT_TEST_INSTALL='true' DOCKER_BASE_IMAGE=nvidia/cuda:9.0-cudnn7-devel-ubuntu16.04 AUTOWARE_COMPILE_WITH_CUDA=ON
    - ROS_DISTRO="melodic" _GUARD_INTERVAL=10 CATKIN_PARALLEL_JOBS='-p2' ROS_PARALLEL_JOBS='-j2' NOT_TEST_BUILD='true' NOT_TEST_INSTALL='true' BUILDER=colcon
    - ROS_DISTRO="melodic" _GUARD_INTERVAL=10 CATKIN_PARALLEL_JOBS='-p2' ROS_PARALLEL_JOBS='-j2' NOT_TEST_BUILD='true' NOT_TEST_INSTALL='true' DOCKER_BASE_IMAGE=nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04 BUILDER=colcon

install:
  - git clone --branch colcon --quiet --depth 1 https://github.com/ipa-mdl/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh